version: '3'

services:

  ui:
    build: ./ui
    ports:
      - "8080:8080"
    restart: unless-stopped

  resource:
    build: ./resource
    restart: unless-stopped

  consent:
    build: ./consent
    ports:
      - "3000:3000"
    restart: unless-stopped
