introspect:
  url: http://127.0.0.1:4445/oauth2/introspect

server:
  port: 9000

spring:
  security:
    oauth2:
      resourceserver:
        opaquetoken:
          introspection-uri: ${introspect.url}
          client-id: ${client.id:auth-code-client}
          client-secret: ${client.secret:}

logging:
  level:
    org.springframework.security: DEBUG

---

spring:
  profiles:
  - container

introspect:
  url: http://hydra:4445/oauth2/introspect

server:
  port: 8080

---

spring:
  profiles:
  - gcp

introspect:
  url: https://bejaw.crabdance.com/oauth2/introspect

---

spring:
  profiles:
  - azure

azure:
  graph: https://graph.microsoft.com
  user-info-uri: ${azure.graph}/oidc/userinfo

---

spring:
  profiles:
  - okta

introspect:
  url: https://dev-188673.okta.com/oauth2/default/v1/introspect

client:
  id: 0oa14lg1vzLXZrnTz4x6
  secret: 'QDYGdeCEt1VnblULDxrwgGT_5XJ6rtmti1OCJ-Yu'