hydra:
  url: http://127.0.0.1:4445

server:
  port: 9000

spring:
  security:
    oauth2:
      resourceserver:
        opaquetoken:
          introspection-uri: ${hydra.url}/oauth2/introspect
          client-id: 
          client-secret: 

logging:
  level:
    org.springframework.security: DEBUG

---

spring:
  profiles:
  - container

hydra:
  url: http://hydra:4445

server:
  port: 8080
