apiVersion: v1
kind: Service
metadata:
  name: hydra
spec:
  type: NodePort

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: hydra-config
data:
  URLS_SELF_ISSUER: https://awjaw.crabdance.com
  URLS_CONSENT: https://cowjaw.crabdance.com/consent
  URLS_LOGIN: https://cowjaw.crabdance.com/login
  URLS_LOGOUT: https://cowjaw.crabdance.com/logout
