apiVersion: apps/v1
kind: Deployment
metadata:
  name: hydra
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: hydra
        image: oryd/hydra
        command:
        - hydra
        - serve
        - all
        - --dangerous-force-http
        ports:
          - containerPort: 4444
            hostPort: 4444
            name: hydra
          - containerPort: 4445
            hostPort: 4445
            name: admin
          - containerPort: 5555
            hostPort: 5555
            name: extra
        env:
        - name: URLS_SELF_ISSUER
          value: http://127.0.0.1:4444
        - name: URLS_CONSENT
          value: http://127.0.0.1:3000/consent
        - name: URLS_LOGIN
          value: http://127.0.0.1:3000/login
        - name: URLS_LOGOUT
          value: http://127.0.0.1:3000/logout
        - name: DSN
          value: memory
        - name: SECRETS_SYSTEM
          value: youReallyNeedToChangeThis
        - name: OIDC_SUBJECT_TYPES_SUPPORTED
          value: public,pairwise
        - name: OIDC_SUBJECT_TYPE_PAIRWISE_SALT
          value: youReallyNeedToChangeThis
      - name: consent
        image: oryd/hydra-login-consent-node:v1.0.0-rc.10
        ports:
          - containerPort: 3000
            hostPort: 3000
            name: http
        env:
        - name: HYDRA_ADMIN_URL
          value: http://127.0.0.1:4445

---

apiVersion: v1
kind: Service
metadata:
  name: hydra
spec:
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      name: consent
    - protocol: TCP
      port: 4444
      targetPort: 4444
      name: hydra
    - protocol: TCP
      port: 4445
      targetPort: 4445
      name: admin
