apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: ui
        image: dsyer/oauth2-ui

---

apiVersion: v1
kind: Service
metadata:
  name: ui
spec:
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: http
