
hydra:
  url: http://127.0.0.1:4444
  redirect: http://127.0.0.1:4444

resource:
  url: http://localhost:9000

spring:
  security:
    oauth2:
      client:
        registration:
          hydra:
            scope: openid,offline
            client-id: auth-code-client
            client-secret: secret
            authorization-grant-type: authorization_code
            redirect-uri: '{baseUrl}/{action}/oauth2/code/{registrationId}'
        provider:
          hydra:
            authorization-uri: ${hydra.redirect}/oauth2/auth
            token-uri: ${hydra.url}/oauth2/token
            user-info-uri: ${hydra.url}/userinfo
            jwk-set-uri: ${hydra.url}/.well-known/jwks.json

logging:
  level:
    org.springframework.security: DEBUG

---

spring:
  profiles:
  - container

hydra:
  url: http://hydra:4444

resource:
  url: http://resource:8080

