
hydra:
  url: http://127.0.0.1:4444
  redirect: http://127.0.0.1:4444

azure:
  url: https://login.microsoftonline.com
  graph: https://graph.microsoft.com

okta:
  url: https://dev-188673.okta.com

resource:
  url: http://localhost:9000

spring:
  security:
    oauth2:
      client:
        registration:
          hydra:
            client-name: Hydra
            scope: openid,offline
            client-id: auth-code-client
            client-secret: secret
            authorization-grant-type: authorization_code
            redirect-uri: '{baseUrl}/{action}/oauth2/code/{registrationId}'
          azure:
            client-name: Azure
            scope: openid
            client-id: 352d4c81-6e20-4de9-a746-e9126e528b08
            client-secret: Lt8mB=jF-OvJH-j/zYReFcjvF4yTLI55
            authorization-grant-type: authorization_code
            redirect-uri: '{baseUrl}/{action}/oauth2/code/{registrationId}'
          okta:
            scope: openid
            client-id: 0oa14lg1vzLXZrnTz4x6
            client-secret: 'QDYGdeCEt1VnblULDxrwgGT_5XJ6rtmti1OCJ-Yu'
            authorization-grant-type: authorization_code
        provider:
          hydra:
            authorization-uri: ${hydra.redirect}/oauth2/auth
            token-uri: ${hydra.url}/oauth2/token
            user-info-uri: ${hydra.url}/userinfo
            jwk-set-uri: ${hydra.url}/.well-known/jwks.json
          azure:
            authorization-uri: ${azure.url}/common/oauth2/v2.0/authorize
            token-uri: ${azure.url}/common/oauth2/v2.0/token
            user-info-uri: ${azure.graph}/oidc/userinfo
            jwk-set-uri: ${azure.url}/common/discovery/v2.0/keys
            user-name-attribute: sub
          okta:
            authorization-uri: ${okta.url}/oauth2/default/v1/authorize
            token-uri: ${okta.url}/oauth2/default/v1/token
            jwk-set-uri:  ${okta.url}/oauth2/default/v1/keys

logging:
  level:
    org.springframework.security: DEBUG

---

spring:
  profiles:
  - container

hydra:
  url: http://hydra:4444

resource:
  url: http://resource:8080

---

spring:
  profiles:
  - crabdance

hydra:
  url: https://awjaw.crabdance.com
  redirect: https://awjaw.crabdance.com
