apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- hydra.yaml
commonLabels:
  app: hydra
configMapGenerator:
- name: hydra-config
  literals:
  - URLS_SELF_ISSUER=http://127.0.0.1:4444
  - URLS_CONSENT=http://127.0.0.1:3000/consent
  - URLS_LOGIN=http://127.0.0.1:3000/login
  - URLS_LOGOUT=http://127.0.0.1:3000/logout
  - HYDRA_ADMIN_URL=http://127.0.0.1:4445
