apiVersion: apps/v1
kind: Deployment
metadata:
  name: resource
  labels:
    app: resource
spec:
  replicas: 1
  selector:
    matchLabels:
      app: resource
  template:
    metadata:
      labels:
        app: resource
    spec:
      containers:
      - name: resource
        image: dsyer/oauth2-resource

---

apiVersion: v1
kind: Service
metadata:
  name: resource
  labels:
    app: resource
spec:
  selector:
    app: resource
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: http
